/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.test.java.rita;

import org.junit.Test;

import rita.RiTa;
import static org.junit.Assert.*;

public class RiTaTest {

    @Test public void testSomeLibraryMethod() {
        
    }
}
