/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rita.test;

import org.junit.Test;

import rita.RiTa;
import static org.junit.Assert.*;

public class RiTaTest
{
  
  @Test
  public void testIsPunctuation()
  {
    assertFalse(RiTa.isPunctuation("The dog"));
    assertFalse(RiTa.isPunctuation("The dog."));
    assertTrue(RiTa.isPunctuation("."));
  }
}
