/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rita.test;


import org.junit.Test;

import rita.*;
import static org.junit.Assert.*;


public class TaggerTests {
	
	

    @Test 
    public void testisQuestion() {

    
    }
    
}
